[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.gd', 'php82Extensions.bcmath', 'php82Extensions.intl', 'nodejs_18', 'npm-9_x', 'postgresql']

[phases.install]
cmds = [
    'composer install --ignore-platform-reqs --no-scripts',
    'npm install'
]

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan octane:frankenphp --host=0.0.0.0 --port=$PORT --max-requests=500'

